# mbc3-restore-final-grade
# revision: mbc3-final-20260425-restore-v2
# Purpose:
#   Restore MobileBandChange3 persisted globals from the mbc3-state script.
#
# Contract:
#   - mbc3-state is generated by mbc3-save-final-grade.
#   - Restore refuses to run state if required markers are missing.
#   - mbc3RestoreDone is set true in every exit path.
#   - mbc3LogInited is intentionally not restored; first post-reboot run emits clean init.

:global mbc3RestoreDone

:local tag "[mbc3-restore] "
:local stateScript "mbc3-state"
:local markerStart "# MBC3-STATE-V1"
:local markerEnd "# MBC3-STATE-END"
:local minLen 300
:local maxLen 60000

:do {
    :local sid [/system script find where name=$stateScript]

    :if ([:len $sid] = 0) do={
        :log info ($tag . "SAFE no saved state found - cold start")
        :set mbc3RestoreDone true
        :return
    }

    :local src [/system script get $sid source]
    :local srcLen [:len $src]

    :if ($srcLen < $minLen) do={
        :log warning ($tag . "SAFE saved state too short - cold start srcLen=" . $srcLen)
        :set mbc3RestoreDone true
        :return
    }

    :if ($srcLen > $maxLen) do={
        :log error ($tag . "DISRUPTIVE saved state too large - refused srcLen=" . $srcLen)
        :set mbc3RestoreDone true
        :return
    }

    :if ([:find $src $markerStart] = nil) do={
        :log warning ($tag . "SAFE saved state marker missing - cold start")
        :set mbc3RestoreDone true
        :return
    }

    :if ([:find $src $markerEnd] = nil) do={
        :log warning ($tag . "SAFE saved state end marker missing - cold start")
        :set mbc3RestoreDone true
        :return
    }

    /system script run $stateScript
    :log info ($tag . "state restored from " . $stateScript . " srcLen=" . $srcLen)
    :set mbc3RestoreDone true
} on-error={
    :log warning ($tag . "SAFE failed to restore from " . $stateScript . " - cold start")
    :set mbc3RestoreDone true
}
